services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ..:/app
    command: [
      "uvicorn",
      "main:app",
      "--app-dir", "apps/api/src",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--log-level", "info"
    ]
