services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ..:/app
    command: [
      "uvicorn",
      "main:app",
      "--app-dir", "apps/api/src",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--log-level", "info"
    ]

  webapp:
    image: node:20-bullseye
    working_dir: /app/apps/webapp
    ports:
      - "5173:5173"
    volumes:
      - ..:/app
    command: bash -lc "corepack enable && corepack prepare yarn@1.22.22 --activate && yarn install && yarn dev --host"
