name: Build and Push Workflow

on:
  push:
    branches: [ red-teaming-agent-cicd ]
    paths:
      - 'testapps/api/**'

permissions:
  id-token: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and deploy Frontend Container App
      uses: azure/container-apps-deploy-action@v2
      with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./testapps/api/Dockerfile
          imageToBuild: ${{ secrets.ACR_NAME }}.azurecr.io/rt-api:latest
          acrName: ${{ secrets.ACR_NAME }}
          containerAppName: ${{ secrets.CONTAINER_APP_NAME }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
