name: Run AI Red Teaming Scan

on:
  schedule:
    - cron: '0 2 * * 0'  # Run every Sunday at 2 AM UTC

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install poetry
      uses: abatilo/actions-poetry@v4

    - name: Install Red Team dependencies
      run: poetry install --directory=spikes/red-teaming-agent

    - name: Run Red Teaming Scan
      env:
        AZURE_AI_FOUNDRY_ENDPOINT: ${{ secrets.AZURE_AI_FOUNDRY_ENDPOINT }}
        TARGET_ENDPOINT: ${{ secrets.TARGET_ENDPOINT }}
      run: poetry run python spikes/red-teaming-agent/ai-foundry-redteam-agent.py
